include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Impulse Counter
APP_DEPENDS:=+impulse-counter +data-sender-api-mod-impulse_counter

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
