include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for SMPP

APP_TLT_NAME:=SMPP
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=smpp
APP_HW_INFO:=mobile

include ../app.mk

define Package/vuci-app-smpp-ui/description
	SMPP package that provides SMPP protocol
	services for flexible short message data transfer.
endef

# call BuildPackage - OpenWrt buildroot signature
