#!/bin/sh
set -e

lua_script(){
	lua_script='
	local jsonc = require("luci.jsonc")
	local file_path = "/etc/certificates/status/info"
	local target_fullname = "'"$1"'"
	local new_datetime = "'"$2"'"
	local scep_url = "'"$3"'"
	local converted_date = new_datetime:gsub("^notAfter=", ""):gsub(" ", "T")

	-- Function to read JSON file
	local function read_json(file)
		local f = io.open(file, "r")
		if not f then
			error("Cannot open file for reading: " .. file)
		end
		local content = f:read("*a")
		f:close()
		local obj, err = jsonc.parse(content)
		if err then
			error("Error parsing JSON: " .. err)
		end
		return obj
	end

	local function write_json(file, data)
		local f = io.open(file, "w")
		if not f then
			error("Cannot open file for writing: " .. file)
		end
		local content = jsonc.stringify(data)
		f:write(content)
		f:close()
	end

	local data = read_json(file_path)

	for _, item in ipairs(data) do
		if item.fullname == target_fullname then
			item.datetime = converted_date
			item.scep_url = scep_url
			break
		end
	end
	write_json(file_path, data)
	'
	echo "$lua_script" | /usr/bin/lua
}

##############################################################################
# Set local paths 
#

# Path to the Vuci certificate folder 
CERT_PATH="/etc/certificates"

##############################################################################
# Change into the certificates directory
#
cd $CERTDIR

##############################################################################
# Install the private key and certificate
#
ln -sf "$CERTDIR/$HOSTKEY" "$CERT_PATH/$FQDN.key.pem"
ln -sf "$CERTDIR/$HOSTCERT" "$CERT_PATH/$FQDN.cert.pem"
ln -sf "$CERTDIR/$ROOTCA" "$CERT_PATH/ca-$FQDN.cert.pem"

enddate_cert=$(openssl x509 -enddate -noout -dateopt iso_8601 -in "$CERTDIR/$HOSTCERT")
enddate_ca=$(openssl x509 -enddate -noout -dateopt iso_8601 -in "$CERTDIR/$ROOTCA")

FQDN="${FQDN//\`/\\\`}"
FQDN="${FQDN//\'/\\\'}"
FQDN="${FQDN//\"/\\\"}"

lua_script $FQDN.cert.pem "$enddate_cert" "$SCEP_URL"
lua_script ca-$FQDN.cert.pem "$enddate_ca" "$SCEP_URL"

cron="0 0 * * 0 FQDN="$FQDN" SCEP_URL="$SCEP_URL" /usr/sbin/cert-enroll.sh"
if ! crontab -l | grep -q 'FQDN='"$FQDN"' SCEP_URL='"$SCEP_URL"' /usr/sbin/cert-enroll.sh"'; then
	(crontab -l ; echo "${cron}")| crontab -
	logger "Updated crontab with new entry: \'${cron}\'"
fi

exit 0