#!/bin/sh

. /lib/functions.sh

change_monitoring_action(){
	local section_id="$1"
	local action

	config_get action "$section_id" "action"

	if [ "$action" = "iostatus" ]; then
		uci_set "sms_utils" "$section_id" "action" "send_status"
	fi

}

config_load "sms_utils"
config_foreach change_monitoring_action "rule"
uci_commit "sms_utils"

exit 0
