#!/bin/sh

. /lib/functions.sh

IP_BLOCKD_CFG="ip_blockd"

set_vars() {
    local section="$1"
    config_get enabled "$section" "enabled"
    config_get reboot_clear "$section" "reboot_clear"
    [ -z "$enabled" ] && uci_set "$IP_BLOCKD_CFG" "$section" "enabled" "1"
    [ -z "$reboot_clear" ] && uci_set "$IP_BLOCKD_CFG" "$section" "reboot_clear" "0"
}

config_load "$IP_BLOCKD_CFG"
config_foreach set_vars globals

uci_commit "$IP_BLOCKD_CFG"

exit 0
