#!/bin/sh

. /lib/functions.sh

CONFIG="rms_mqtt"
SECTION="rms_connect_timer_level"

delete_existing_rms_connect_timer_levels() {
	local section="$1"
	uci_remove "$CONFIG" "$section"
}

add() {
	uci_add "$CONFIG" "$SECTION"
	uci_set "$CONFIG" "$CONFIG_SECTION" "repeat_time" "$1"
	uci_set "$CONFIG" "$CONFIG_SECTION" "whole_time" "$2"
}

config_load "$CONFIG"

config_foreach delete_existing_rms_connect_timer_levels "$SECTION"

add "120" "3600"
add "300" "3600"
add "600" "3600"
add "3600" "1209600"

uci_commit "$CONFIG"
