include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Modbus
APP_DEPENDS:=+modbus_client +vuci-app-data-sender-api-mod-modbus +vuci-app-data-sender-api-mod-modbus-alarm

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
