include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support Dynamic routes nhrp application

include ../app.mk

define Package/vuci-app-dynamic-routes-nhrp-ui/description
	Next Hop Resolution Protocol (NHRP) is a protocol or method that can
	be used so that a computer sending data to another computer can learn
	the most direct route (the fewest number of hops) to the receiving computer. 
endef

# call BuildPackage - OpenWrt buildroot signature
