include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for IEC 60870-5 Client

APP_DEPENDS:=+iec60870_client +vuci-app-data-sender-api-mod-iec60870

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
