#!/bin/sh

. /lib/functions.sh
PACKAGE_FILE="/etc/package_restore.txt"

[ -s "$PACKAGE_FILE" ] && {
	sed -i "s/frr-bgpd/frr8-bgpd/g" "$PACKAGE_FILE"
	sed -i "s/frr-ripd/frr8-ripd/g" "$PACKAGE_FILE"
	sed -i "s/frr-ospfd/frr8-ospfd/g" "$PACKAGE_FILE"
	sed -i "s/frr-eigrpd/frr8-eigrpd/g" "$PACKAGE_FILE"
	sed -i "s/frr-nhrp/frr8-nhrp/g" "$PACKAGE_FILE"
	sed -i "s/frr-bfdd/frr8-bfdd/g" "$PACKAGE_FILE"
	sed -i "s/frr-vtysh/frr8-vtysh/g" "$PACKAGE_FILE"
	sed -i "s/dmvpn /dmvpn_frr8 /g" "$PACKAGE_FILE"
	sed -i "s/bfdd-frr /bfdd-frr8 /g" "$PACKAGE_FILE"
	sed -i "s/mpls /mpls8 /g" "$PACKAGE_FILE"
}

exit 0
