include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for OPCUA

APP_TLT_NAME:=OPC UA Client
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=opcua_client

include ../app.mk

define Package/vuci-app-opcua-ui/description
	OPC UA client designed for reading data from OPC UA servers and storing read data in local database.
endef

# call BuildPackage - OpenWrt buildroot signature
