#!/bin/sh

section="${PLUTO_CONNECTION##*-}"

ifname="$(uci -q get ipsec.$section.bind_to)"
[ -z "$ifname" ] || [ "$ifname" = "-" ] && exit 0

check_cl="$(uci -q get network.$ifname.proto)"
[ "$check_cl" = "l2tp" ] || exit 0

echo "Setting up L2TP $ifname over IPsec"

if [ "$PLUTO_VERB" = "up-host" ]; then
	logger -t "ipsec" "Interface '$ifname' bringing up L2TP over IPsec connection"
    ifup "$ifname"
elif [ "$PLUTO_VERB" = "down-host" ]; then
	logger -t "ipsec" "Interface '$ifname' bringing down L2TP over IPsec connection"
    ifdown "$ifname"
fi
