include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for MPLS

include ../app.mk

define Package/vuci-app-mpls-ui/description
	Multiprotocol Label Switching (MPLS) is a routing technique that uses labels instead of network addresses for routing decisions 
endef

# call BuildPackage - OpenWrt buildroot signature
