include $(TOPDIR)/rules.mk

PKG_LICENSE:=Teltonika-nda-source

APP_TITLE:=VuCI API Support for SIM Idle protection

APP_DEPENDS:=+sim_idle_protection

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
