include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support Dynamic routes nhrp application

APP_DEPENDS:=+SMALL_FLASH:frr8-nhrp +!SMALL_FLASH:frr-nhrp

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
