#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Teltonika

START=51

USE_PROCD=1
PROG="/usr/sbin/telnetd"
NAME=telnetd
PIDCOUNT=0

service_triggers() {
	procd_add_reload_trigger "telnetd" "system"
}

start_instance() {
	local enabled port

	config_get enabled "$1" enable 0
	[ "$enabled" -ne 1 ] && return 0
	config_get port "$1" port 23

	PIDCOUNT="$(( ${PIDCOUNT} + 1))"
	local banner_enabled="$(uci -q get system.banner.enabled)"

	procd_open_instance
	procd_set_param command "$PROG" -F -p "$port" 
	if [ -n "$banner_enabled" ] && [ "$banner_enabled" -eq 1 ]; then
		local banner_file="/var/run/${NAME}.${PIDCOUNT}.banner"
		echo -e "*** $(uci -q get system.banner.title) ***" > $banner_file
		echo -e "\n$(uci -q get system.banner.message)" >> $banner_file
		procd_append_param command -f "$banner_file"
		procd_set_param file "/etc/config/system"
	fi
	procd_close_instance
}

start_service() {
	config_load "telnetd"
	config_foreach start_instance "telnetd"
}
