include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for OpenConnect

APP_APP_NAME:=openconnect
APP_TLT_NAME:=OpenConnect
APP_ROUTER:=$(TLT_PLATFORM_NAME)

include ../app.mk

define Package/vuci-app-openconnect-ui/description
	OpenConnect is a cross-platform multi-protocol SSL VPN client which supports a number of VPN protocols:
	Cisco AnyConnect, Array Networks SSL VPN, Juniper SSL VPN,
	Pulse Connect Secure, Palo Alto Networks GlobalProtect SSL VPN,
	F5 Big-IP SSL VPN, Fortinet Fortigate SSL VPN
endef

# call BuildPackage - OpenWrt buildroot signature
