include $(TOPDIR)/rules.mk

APP_TITLE:=Japanese Language Support (日本語)
LANGUAGE:=ja
LANG_LONG_NAME:=japanese
LANGUAGE_STRING:=日本語

VERSION:=2023-01-16

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
