include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI Support for BACnet

APP_TLT_NAME:=BACnet Router
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=bacnet-router

include ../app.mk

define Package/vuci-app-bacnet-ui/description
  Bacnet router application is designed for communication between BACnet IP and MS/TP serial networks.
endef

# call BuildPackage - OpenWrt buildroot signature
