#!/bin/sh

. /lib/functions.sh

update_dhcpv6()  {
	local section="$1"
	local dhcpv6 ndp ra

	config_get dhcpv6 "$section" dhcpv6 ""
	config_get ra "$section" ra ""
	config_get ndp "$section" ndp ""

	if [ -z "$dhcpv6" ] && [ -z "$ra" ] && [ -z "$ndp" ]; then
		uci_set "dhcp" "$section" "ignore_ipv6" "1"
	fi
}

config_load dhcp
config_foreach update_dhcpv6 dhcp
uci_commit "dhcp"

exit 0
