include $(TOPDIR)/rules.mk

APP_TITLE:=Ukrainian Language Support (Українська)
LANGUAGE:=ua
LANG_LONG_NAME:=ukrainian
LANGUAGE_STRING:=Українська

VERSION:=2025-01-16

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
