#!/bin/sh /etc/rc.common

START=15

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param user uhttpd
	procd_set_param group uhttpd
	procd_set_param stderr 1
	procd_set_param command /sbin/event_server
	procd_close_instance
}

