include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support Dynamic routes rip application

APP_DEPENDS:=+SMALL_FLASH:frr8-ripd +!SMALL_FLASH:frr-ripd +!SMALL_FLASH:frr-vtysh

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
