include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Cumulocity/Cloud of Things

APP_TLT_NAME:=Cumulocity - Cloud of Things
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=cmStreamApp

include ../app.mk


define Package/vuci-app-cumulocity-ui/description
	Cumulocity - Cloud of Things IoT application meant
	for interaction with cloud-based Cumulocity IoT platform and
	Telekom Cloud of Things.
endef


# call BuildPackage - OpenWrt buildroot signature
