#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.GPSInfo."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_GPSInfo"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_GPSInfo"

entry_execute_method_root_GPSInfo() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.GPSInfo."*)
                common_execute_method_obj "$DMROOT.GPSInfo." "0"
		common_execute_method_param "$DMROOT.GPSInfo.Latitude" "0" "get_latitude" "" "" "1"
		common_execute_method_param "$DMROOT.GPSInfo.Longitude" "0" "get_longitude" "" "" "1"
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#   Data model parameters functions   #
#######################################

get_latitude()
{
        json_load "$(ubus call gpsd position)"
        json_get_var received_latitude latitude

        echo "$received_latitude"
}

get_longitude()
{
        json_load "$(ubus call gpsd position)"
        json_get_var received_longitude longitude

        echo "$received_longitude"
}
