include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Wifi scanner
APP_DEPENDS=+wifi_scanner +vuci-app-data-sender-api-mod-wifiscan

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
