include $(TOPDIR)/rules.mk

APP_TITLE:=Polish Language Support (Polski)
LANGUAGE:=pl
LANG_LONG_NAME:=polish
LANGUAGE_STRING:=Polski

VERSION:=2026-01-07

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
