include $(TOPDIR)/rules.mk

APP_TITLE:=Portuguese Language Support (Português)
LANGUAGE:=pt
LANG_LONG_NAME:=portuguese
LANGUAGE_STRING:=Português

VERSION:=2023-01-16

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
