include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for 802.1X Client

NO_API_DEPEND:=y
APP_DEPENDS:=+vuci-app-port-security-api

include ../app.mk

# call BuildPackage - OpenWrt buildroot signature
