#!/bin/sh

. /lib/functions.sh

commit=0

if [ -z "$(uci_get uhttpd main ubus_prefix)" ]; then
	uci_set "uhttpd" "main" "ubus_prefix" "/ubus"
	commit=1
fi

[ "$(uci_get uhttpd main ubus_socket)" = "/var/run/ubus.sock" ] && {
	uci_set "uhttpd" "main" "ubus_socket" "/var/run/ubus/ubus.sock"
	commit=1
}

[ "$commit" = 1 ] && uci_commit "uhttpd" && /etc/init.d/uhttpd reload

exit 0
