#!/bin/sh

. /lib/functions.sh

which setcap > /dev/null || exit 0

for file in $(grep -sl Capabilities /usr/lib/opkg/info/*.control); do
	file="${file##*/}"
	file="${file%.control}"
	set_capabilities "$file"
done
