include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for ThingWorx

APP_TLT_NAME:=ThingWorx
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=twStreamApp

include ../app.mk

define Package/vuci-app-thingworx-ui/description
	Thingworx is a package meant for interaction with
	industrial innovation platform ThingWorx.
endef

# call BuildPackage - OpenWrt buildroot signature
