#!/bin/sh

service=$(uci -q get "network.${IFNAME#*-}.proto")
[ "$service" != "pptp" ] && exit 0 # Not pptp interface, exit

[ -f /var/state/pptp/"${IFNAME#*-}".status ] && rm /var/state/pptp/"${IFNAME#*-}".status
exit 0
