#
# Copyright (C) 2014 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=sqm-scripts
PKG_VERSION:=1.5.1
PKG_RELEASE:=2

PKG_SOURCE_PROTO:=git
PKG_SOURCE_VERSION:=v1.5.1
PKG_SOURCE_URL:=https://github.com/tohojo/sqm-scripts.git


PKG_MAINTAINER:=Toke Høiland-Jørgensen <toke@toke.dk>
PKG_LICENSE:=GPL-2.0-only

include $(INCLUDE_DIR)/package.mk

define Package/sqm-scripts
  SECTION:=net
  CATEGORY:=Base system
  DEPENDS:=+tc +kmod-sched-core +kmod-ifb +iptables \
	+iptables-mod-ipopt +iptables-mod-conntrack-extra \
	+kmod-sched-cake
  TITLE:=SQM Scripts (QoS)
  PKGARCH:=all
endef

define Package/sqm-scripts/description
 A set of scripts that does simple SQM configuration.
endef

define Package/sqm-scripts/conffiles
/etc/config/sqm
/etc/sqm/sqm.conf
endef

define Package/sqm-scripts/install
	$(eval USR_DIR:=$$(1)$(if $(findstring m,$(CONFIG_PACKAGE_sqm-scripts)),,/usr/local))
	make -C $(PKG_BUILD_DIR) USRDIR=$(USR_DIR) DESTDIR=$(1) PLATFORM=openwrt install
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_CONF_USR) ./files/sqm.conf $(1)/etc/config/sqm
endef

$(eval $(call BuildPackage,sqm-scripts))
