include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Side Widget controller API

define Package/vuci-app-side-widget-api/conffiles
/etc/config/widget
endef

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
