include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for AWS Greengrass

APP_TLT_NAME:=AWS Greengrass Core
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=greengrass

include ../app.mk

define Package/vuci-app-greengrass-ui/description
	AWS Greengrass Core is a service meant for communication
	with Amazon Web Services Greengrass Core cloud software.
endef

# call BuildPackage - OpenWrt buildroot signature
