include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support Dynamic routes rip application

include ../app.mk

define Package/vuci-app-dynamic-routes-rip-ui/description
	The Routing Information Protocol (RIP) is one of the
	oldest distance-vector routing protocols which employ
	the hop count as a routing metric.
endef

# call BuildPackage - OpenWrt buildroot signature
