include $(TOPDIR)/rules.mk

APP_TITLE:=Turkish Language Support (Türkçe)
LANGUAGE:=tr
LANG_LONG_NAME:=turkish
LANGUAGE_STRING:=Türkçe

VERSION:=2023-01-16

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
