include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for EoIP

APP_APP_NAME:=eoip
APP_TLT_NAME:=EoIP
APP_ROUTER:=$(TLT_PLATFORM_NAME)

include ../app.mk

define Package/vuci-app-eoip-ui/description
	linux-eoip can create ethernet tunnels compatible with Mikrotik EoIP tunnel.
	At current moment it is easiest way to create stateless tunnel with Mikrotik.
endef

# call BuildPackage - OpenWrt buildroot signature
