include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for OPC UA server

APP_TLT_NAME:=OPC UA Server
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=opcua_server

include ../app.mk

define Package/vuci-app-opcua-server-ui/description
	OPC UA server designed for OPC UA clients to read device data.
endef

# call BuildPackage - OpenWrt buildroot signature
