include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support Dynamic routes ospf application

APP_DEPENDS:=+SMALL_FLASH:frr8-ospfd +!SMALL_FLASH:frr-ospfd

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
