include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Zerotier

APP_APP_NAME:=zerotier
APP_TLT_NAME:=ZeroTier
APP_ROUTER:=$(TLT_PLATFORM_NAME)

include ../app.mk

define Package/vuci-app-zerotier-ui/description
	ZeroTier package can establish Peer to Peer VPN (P2PVPN) connection
	between various devices running various operating systems. It also provides
	network management possibilities such as routing and creating firewall rules.
endef

# call BuildPackage - OpenWrt buildroot signature
