#!/bin/sh
. /lib/functions.sh

update_certs() {
	local int="$1"
	local proto ca 
	config_get proto "$int" "proto"
	[ "$proto" != "sstp" ] && return 0
	config_get ca "$int" ca
	[ -f "$ca" -a "$(dirname "$ca")" = "/etc/vuci-uploads" ] && {
		chmod 660 "$ca"
		chown sstpc:certificates "$ca"
	}
}

config_load network
config_foreach update_certs interface
exit 0