#!/bin/sh
. /lib/functions.sh

migrate_connm_to_wwan() {
	local section="$1"
	local proto
	config_get "proto" "$section" "proto"
	[ "$proto" = "connm" ] || return
	uci set "network.$section.proto=wwan"
}

config_load network
config_foreach migrate_connm_to_wwan interface
uci commit network
exit 0
