#!/bin/sh

. /lib/functions.sh

change_table() {
	local section="$1"
	config_get "service" "$section" "service"
	[ "$service" != "dmvpn" ] && return
	config_get "table" "$section" "table"
	[ "$table" = "main" ] && uci_set "network" "$section" "table" "254"
}

config_load "network"
config_foreach "change_table" "route"
uci_commit "network"

