include $(TOPDIR)/rules.mk

APP_TITLE:=German Language Support (Deutsch)
LANGUAGE:=de
LANG_LONG_NAME:=german
LANGUAGE_STRING:=Deutsch

VERSION:=2023-01-16

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
