#!/bin/sh

. /lib/functions.sh

[ "$(uci_get dhcp @dnsmasq[0] resolvfile)" = "/tmp/resolv.conf.auto" ] && {
	uci_set "dhcp" "@dnsmasq[0]" "resolvfile" "/tmp/resolv.conf.d/resolv.conf.auto"
	uci_commit "dhcp"
}

exit 0
