#!/bin/sh

. /lib/functions.sh

[ -f "/etc/config/teltonika" ] && {
    cp /rom/etc/config/rpcd /etc/config/rpcd
    exit 0
}

login_cb() {
    local sec="$1"
    local username password

    config_get username "$sec" "username"
    [ "$username" != "admin" ] && return

    config_get password "$sec" "password"
    [ "$password" == "\$p\$root" ] && \
        uci_set rpcd "$sec" "password" "\$p\$admin"
}

config_load "rpcd"
config_foreach login_cb "login"
config_foreach login_cb "superuser"
uci_commit "rpcd"

exit 0
