#!/bin/sh

. /lib/functions.sh

# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@mwan3[-1]
	add ucitrack mwan3
	set ucitrack.@mwan3[-1].exec="/etc/init.d/mwan3 reload"
	commit ucitrack
EOF

uci_get "mwan3" "globals" >/dev/null || {
	uci_add "mwan3" "globals" >/dev/null
	uci_rename "mwan3" "@globals[-1]" "globals" >/dev/null
	uci_set "mwan3" "globals" "local_source" "none" >/dev/null
	uci_commit "mwan3"
}

# remove LuCI cache
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
