#!/bin/sh

. /lib/functions.sh

#UHTTPD START
#IPV6 MIGRATION

main_http=$(uci_get uhttpd main listen_http)
main_https=$(uci_get uhttpd main listen_https)
hotspot_http=$(uci_get uhttpd hotspot listen_http)
hotspot_https=$(uci_get uhttpd hotspot listen_https)
[ -n "$main_http" ] && [ "$main_http" != "${main_http##*:}" ] && uci_set "uhttpd" "main" "listen_http" "${main_http##*:}"
[ -n "$main_https" ] && [ "$main_https" != "${main_https##*:}" ] && uci_set "uhttpd" "main" "listen_https" "${main_https##*:}"
[ -n "$hotspot_http" ] && [ "$hotspot_http" != "${hotspot_http##*:}" ] && uci_set "uhttpd" "hotspot" "listen_http" "${hotspot_http##*:}"
[ -n "$hotspot_https" ] && [ "$hotspot_https" != "${hotspot_https##*:}" ] && uci_set "uhttpd" "hotspot" "listen_https" "${hotspot_https##*:}"

#UHTTPD TOTSPOT UBUS_PREFIX DELETEION
[ "$(uci_get uhttpd hotspot ubus_prefix)" ] && uci_remove "uhttpd" "hotspot" "ubus_prefix"

uci_commit "uhttpd"
#UHTTPD END

exit 0
