#!/bin/sh

. /lib/functions.sh

[ -f "/etc/config/rms_connect_mqtt" ] && {
  cat /etc/config/rms_connect_mqtt >> /etc/config/rms_mqtt
  rm /etc/config/rms_connect_mqtt
}

[ -f "/etc/config/rms_connect_timer" ] && {
  cat /etc/config/rms_connect_timer >> /etc/config/rms_mqtt
  rm /etc/config/rms_connect_timer
}

config_load rms_mqtt
uci_remove rms_mqtt "rms_connect_mqtt" "debug"
uci_commit "rms_mqtt"

exit 0
