#!/bin/sh

. /lib/functions.sh

[ -f "$UCI_CONFIG_DIR/samba" ] || return 0

fix_browseable() {
        local value
        config_get value $1 browseable
        [ -n "$value" ] || uci_set "samba" "$1" "browseable" "yes"
}                                                                 
 
config_load samba
config_foreach fix_browseable sambashare
uci_commit samba                        
                
exit 0
