#!/bin/sh

[ "$ACTION" = "ifup" ] || exit

method="$(uci get network.${INTERFACE%%_*}.method)"

[ "$method" = "bridge" ] || [ "$method" = "passthrough" ] || exit

. /usr/share/libubox/jshn.sh

# parsing json data                                                                               
json_load "$(ubus call network.interface.${INTERFACE%%_*} status)"        
json_select data                                                          
json_get_var bridge_ipaddr bridge_ipaddr                                

ip route flush table 43
ip route add default via "$bridge_ipaddr" dev br-lan table 43

