#!/bin/sh /etc/rc.common

START=06
USE_PROCD=1
QUIET=""

service_triggers() {
	procd_add_reload_trigger firewall
}

restart() {
	fw3 restart
	procd_send_signal ip_blockd "*" SIGUSR1
	procd_send_signal chilli "*" SIGUSR1
}

start_service() {
	fw3 ${QUIET} start
}

stop_service() {
	fw3 flush
}

reload_service() {
	fw3 reload
}

boot() {
	# Be silent on boot, firewall might be started by hotplug already,
	# so don't complain in syslog.
	QUIET=-q
	start
}
