#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2012 OpenWrt.org

START=80

USE_PROCD=1
PROG=/usr/sbin/relayd

resolve_ifname() {
	grep -qs "^ *$1:" /proc/net/dev && {
		append resolved_ifnames "$1"
	}
}

resolve_network() {
	local ifn
	fixup_interface "$1"
	config_get ifn "$1" ifname
	[ -z "$ifn" ] && return 1
	resolve_ifname "$ifn"
}

service_triggers()
{
	procd_add_reload_trigger "network" "relayd"
	procd_add_raw_trigger "interface.*" 2000 /etc/init.d/relayd reload
}

start_relay() {
	local cfg="$1"
	local enabled

	config_get_bool enabled "$cfg" enabled 0
	[ "$enabled" -eq 0 ] && return 0

	include /lib/network

	local resolved_ifnames
	local net networks
	config_get networks "$cfg" network
	config_load network
	for net in $networks; do
		resolve_network "$net" || {
			return 1
		}
	done

	config_load relayd
	local ifn ifnames
	config_get ifnames "$cfg" ifname
	for ifn in $ifnames; do
		resolve_ifname "$ifn" || {
			return 1
		}
	done

	procd_open_instance
	procd_set_param command "$PROG"

	for ifn in $resolved_ifnames; do
		procd_append_param command -I "$ifn"
		procd_append_param netdev "$ifn"
	done
	local ipaddr
	config_get ipaddr "$cfg" ipaddr
	[ -n "$ipaddr" ] && procd_append_param command -L "$ipaddr"

	local gateway
	config_get gateway "$cfg" gateway
	[ -n "$gateway" ] && procd_append_param command -G "$gateway"

	local expiry # = 30
	config_get expiry "$cfg" expiry
	[ -n "$expiry" ] && procd_append_param command -t "$expiry"

	local retry # = 5
	config_get retry "$cfg" retry
	[ -n "$retry" ] && procd_append_param command -p "$retry"

	local table # = 16800
	config_get table "$cfg" table
	[ -n "$table" ] && procd_append_param command -T "$table"

	local fwd_bcast # = 1
	config_get_bool fwd_bcast "$cfg" forward_bcast 1
	[ $fwd_bcast -eq 1 ] && procd_append_param command "-B"

	local fwd_dhcp # = 1
	config_get_bool fwd_dhcp "$cfg" forward_dhcp 1
	[ $fwd_dhcp -eq 1 ] && procd_append_param command "-D"

	procd_close_instance
}

start_service() {
	config_load relayd
	config_foreach start_relay relayd
}
