include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Modbus TCP over Serial Gateway

include ../app.mk

define Package/vuci-app-modbus-serial-gateway-ui/description
	MODBUS RTU to TCP gateway designed to receive MODBUS TCP message, convert to MODBUS RTU and send it to MODBUS RTU device.
endef

# call BuildPackage - OpenWrt buildroot signature
