include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Tailscale

APP_APP_NAME:=tailscale
APP_TLT_NAME:=Tailscale
APP_ROUTER:=$(TLT_PLATFORM_NAME)

include ../app.mk

define Package/vuci-app-tailscale-ui/description
	Tailscale creates a secure network between your servers, computers,
	and cloud instances. Even when separated by firewalls or subnets.
endef

# call BuildPackage - OpenWrt buildroot signature
