include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support Dynamic routes eigrp application

APP_DEPENDS:=+SMALL_FLASH:frr8-eigrpd +!SMALL_FLASH:frr-eigrpd +vuci-app-vpn-utils-api

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
