include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Azure IoT Hub

APP_TLT_NAME:=Azure IoT Hub
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=azure_iothub

include ../app.mk

define Package/vuci-app-azure-iothub-ui/description
	Azure IoT Hub is a utility meant to interact with
	Microsoft Azure IoT Hub cloud platform.
endef

# call BuildPackage - OpenWrt buildroot signature
