#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

mtu_set() {
	local wan_interface
	[ "$ACTION" = "ifup" ] || [ "$ACTION" = "ifdown" ] || return
	wan_interface="$(ip route show default | awk -F 'dev' '{print $2}' | awk 'NR==1 {print $1}')"
	config_cb() {
		local type="$1"
		local name="$2"
		local proto mtu external_mtu wireguard_mtu new_mtu
		config_get proto "$name" proto ""
		config_get mtu "$name" mtu ""
		[ "$proto" = "wireguard" ] && [ -z "$mtu" ] && [ -n "$wan_interface" ] && [ -n "$name" ] || return
		external_mtu=$(cat /sys/class/net/${wan_interface}/mtu)
		wireguard_mtu=$(cat /sys/class/net/${name}/mtu)
		new_mtu=$(( external_mtu - 80 ))
		[ "$wireguard_mtu" != "$new_mtu" ] && {
			logger -t "wireguard" "Interface $name mtu size changed from $wireguard_mtu to $new_mtu"
			ifconfig "$name" mtu "$new_mtu" up
		}
	}
	config_load network
}


config_load network
mtu_set

for file in /tmp/wireguard/default-status*; do
	[ -f "$file" ] || continue
	DEFAULT_STATUS="${file}"
	# rm "${DEFAULT_STATUS}"
	default="$(ip route show default | grep -w "$DEVICE" )"
	[ -n "$default" ] || exit 0

	config="$(cat "$DEFAULT_STATUS" | sed '2q;d')"
	peer_config="$(cat "$DEFAULT_STATUS" | sed '1q;d')"

	[ "${default##*via }" != "$default" ] && gw=$(echo "${default##*via }" | awk '{print $1}')
	iface="$(echo "$INTERFACE" | sed 's/_4//')"

	[ "$iface" = "$config" ] && exit 0

	for p in $peer_config; do
		config_get endpoint_host "$p" endpoint_host
		config_get tunlink "$p" tunlink
		config_get metric "$iface" metric

		if [ "$ACTION" = "ifup" ]; then
			for host in $endpoint_host; do
				for ip in $(resolveip -4 "$host");do
					if [ -n "$tunlink" ] && [ "$tunlink" != "any" ]; then
						network_get_device tunlink_dev $tunlink
						[ "$tunlink_dev" = "wwan0" ] && { network_get_device tunlink_dev ${tunlink}_4 || network_get_device tunlink_dev ${tunlink}_6; }
						tunlink_gw="$(ip route show default dev $tunlink_dev | awk -F"via " '{print $2}' | sed 's/\s.*$//')"
						if ip route add "$ip" ${tunlink_gw:+via "$tunlink_gw"} dev "$tunlink_dev" metric "1"; then
							route_del="ip route del "$ip" dev "$tunlink_dev" metric 1"
							grep "$route_del" "$DEFAULT_STATUS" || echo "$route_del" >> "$DEFAULT_STATUS"
						fi
						continue
					fi
					if ip route add "$ip" ${gw:+via "$gw"} dev "$DEVICE" metric "$metric"; then
						route_del="ip route del "$ip" dev "$DEVICE" metric $metric"
						grep "$route_del" "$DEFAULT_STATUS" || echo "$route_del" >> "$DEFAULT_STATUS"
					fi
				done
			done
		fi
	done
done
