include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Overview

define Package/vuci-app-overview-api/conffiles
/etc/config/overview
endef

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature

