#!/bin/sh

. /usr/share/libubox/jshn.sh

show () {
	json_init
	json_add_string output "$1"
	json_add_string exit_code "$2"
	json_dump
}

main () {
	case "$1" in
		list) echo '{ "troubleshoot": { "pass": "str" }, "firstboot": { "factory": true }, "userdefaults": {  }, "dmesg": {  }, "drop_caches": { "type": "str"} }' ;;
		call)
			case "$2" in
				troubleshoot)
					read input;
					res="$(/sbin/troubleshoot.sh $(jsonfilter -s $input -e '@.pass'))"
					code=$?
					show "$res" "$code"
				;;
				firstboot)
						read input;
						[ "$(jsonfilter -s $input -e '@.factory')" = "true" ] && args=" -f"
						/sbin/firstboot -y $args > /dev/null
						code=$?
						echo "{ \"result\": $code }"
				;;
				userdefaults)
					/sbin/user_defaults > /dev/null
					# procd implementation used to return error only on fork failure
					echo "{ \"result\": 0 }"
				;;
				dmesg)
					res="$(dmesg)"
					code=$?
					show "$res" "$code"
				;;
				drop_caches)
					read input
					type="$(echo "$input" | jsonfilter -e '@.type' | tr -d '"')"
					case "$type" in 1|2|3) ;; *) show "Invalid type" 1; exit 1;; esac
					echo $type > /proc/sys/vm/drop_caches 2>&1
					code=$?
					echo "{ \"result\": $code }"
				;;
			esac
		;;
	esac
}

main "$@"
