#!/bin/sh

IMAGE_NAME="rutos-focal:v1.1"

PROJDIR="$(pwd)"
HOMEDIR="$PROJDIR:$PROJDIR"
PASSWD="/etc/passwd:/etc/passwd:ro"
GROUP="/etc/group:/etc/group:ro"
HOSTS="/etc/hosts/:/etc/hosts:ro"
USER="$(id -u):$(id -g)"

SUDO=""

# check if docker is installed
which docker &>/dev/null || {
	echo "Docker is not installed, please install it first."
	exit 1
}

# check if docker is running
[ ! -S /var/run/docker.sock ] && {
	# check if systemd-bloatd is installed
	which systemctl &>/dev/null || {
		echo "Docker is not running, systemd is not available."
		echo "Please start Docker service."
		exit 1
	}

	echo "Docker is not running, attempting to start... "
	sudo systemctl start docker
	[ "$?" -ne 0 ] && {
		echo "Unable to start docker."
		exit 1
	}
}

# check docker permissions
[ "$(docker image ls 2>&1 | grep 'permission denied')" ] && {
	echo "Cannot run docker root-less mode, 'sudo' will be used"
	SUDO="sudo"
}

# check if image is built
[ -n "$($SUDO docker images -q "$IMAGE_NAME")" ] || {
	echo "Image $IMAGE_NAME is not built, running docker build..."
	$SUDO docker build -t "$IMAGE_NAME" "$PROJDIR/scripts"
}

$SUDO docker run -it \
	--rm \
	--network host \
	-u "$USER" \
	-w "$PROJDIR" \
	-v "$HOMEDIR" \
	-v "$HOME:$HOME" \
	-v "$PASSWD" \
	-v "$GROUP" \
	-v "$HOSTS" \
	--ulimit "nofile=1024:1048576" \
	$IMAGE_NAME $@
