#!/usr/bin/env bash

IMG_NAME_PREFIX=git.teltonika.lt:4567/docker/buildsys/
IMG_NAME=${IMG_NAME:-${IMG_NAME_PREFIX}tools}
IMG_TAG=${IMG_TAG:-1.7.3}

# Color codes
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

err() {
	echo -e "${RED}==> $1$NC"
}

info() {
	echo -e "${YELLOW}==> $1$NC"
}

# Check for Docker installation
if ! command -v docker &>/dev/null; then
	err "Docker could not be found."
	exit 1
fi

# Chicken and egg problem - cannot reliably check if docker is running before determining correct permissions,
# but permissions check might print wrong information if the docker is not running.

# Permission handling for Docker command
DOCKER_CMD="docker"
if $DOCKER_CMD info -f "{{println .SecurityOptions}}" 2>/dev/null | grep -q rootless; then
	info "Cannot use rootless docker due to file ownership issues. Will proceed with sudo..."
	DOCKER_CMD="sudo docker"
fi
if ! $DOCKER_CMD ps &>/dev/null; then
	info "Docker commands require sudo. Attempting to proceed with sudo..."
	DOCKER_CMD="sudo docker"
fi

# Check if Docker daemon is running
if ! $DOCKER_CMD info &>/dev/null; then
	info "Docker is not running."
	# Check for systemd to start Docker
	if ! command -v systemctl &>/dev/null; then
		err "Systemd not found. Please start Docker manually."
		exit 1
	fi

	info "Attempting to start Docker using systemd..."
	sudo systemctl start docker || {
		err "Failed to start Docker. Please start Docker manually."
		exit 1
	}
	info "Docker started successfully."
fi

# Check if the Docker image and tag exists locally
if ! $DOCKER_CMD image inspect "$IMG_NAME:$IMG_TAG" >/dev/null 2>&1; then
	info "Docker image $IMG_NAME:$IMG_TAG not found locally. Attempting to download..."
	$DOCKER_CMD login "${IMG_NAME%%/*}" -u oauth2 -p aCb3RawxFnwuSZymE7XM 2>/dev/null # a shared token for read-only access to the container registry
	$DOCKER_CMD pull "$IMG_NAME:$IMG_TAG" || {
		err "Failed to download Docker image. Please check the image name and tag."
		exit 1
	}
fi

WORKDIR="$(pwd)"
PASSWD="/etc/passwd"
GROUP="/etc/group"
HOSTS="/etc/hosts"
USER_GROUP="$(id -u "$USER"):$(id -g "$USER")"

CONTAINER_NAME=${IMG_NAME##"$IMG_NAME_PREFIX"}_${WORKDIR}_${IMG_TAG}
CONTAINER_NAME=${CONTAINER_NAME//\//_}
CONTAINER_NAME=${CONTAINER_NAME//__/_}
CONTAINER_NAME=${CONTAINER_NAME//./_}

# Execute Docker run command with dynamic image name and tag

if $DOCKER_CMD ps --all --quiet --filter name="$CONTAINER_NAME" --filter status=exited | grep -q .; then
	$DOCKER_CMD rm "$CONTAINER_NAME"
fi

# Start a long-running container
if ! $DOCKER_CMD ps --all --quiet --filter name="$CONTAINER_NAME" | grep -q .; then
	$DOCKER_CMD run -d \
		--rm \
		--name "$CONTAINER_NAME" \
		--user "$USER_GROUP" \
		--workdir "$WORKDIR" \
		--volume "$HOME:$HOME" \
		--volume "$WORKDIR:$WORKDIR" \
		--volume "$PASSWD:$PASSWD:ro" \
		--volume "$GROUP:$GROUP:ro" \
		--volume "$HOSTS:$HOSTS:ro" \
		--env EXEC_REAL_BUILD=1 \
		--env INSIDE_DOCKER=1 \
		--ulimit "nofile=1024:1048576" \
		"$IMG_NAME:$IMG_TAG" \
		tail -f /toolchain/host/.prepared >/dev/null
fi

$DOCKER_CMD exec -it "$CONTAINER_NAME" "$@"
