include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Email relay


APP_TLT_NAME:=Email Relay
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=emailrelay

include ../app.mk

define Package/vuci-app-email-relay-ui/description
	Emailrelay is a simple SMTP proxy and store-and-forward message transfer agent (MTA).
endef

# call BuildPackage - OpenWrt buildroot signature
