include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for Tinc VPN

APP_APP_NAME:=tinc
APP_TLT_NAME:=Tinc VPN
APP_ROUTER:=$(TLT_PLATFORM_NAME)

include ../app.mk

define Package/vuci-app-tinc-ui/description
	Tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and
	encryption to create a secure private network between hosts on the Internet.
endef

# call BuildPackage - OpenWrt buildroot signature
