include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for BFD

include ../app.mk

define Package/vuci-app-bfd-ui/description
	Protocol intended to detect faults in the bidirectional path between two forwarding engines, including interfaces, data link(s), and to the extent possible the forwarding engines themselves, with potentially very low latency.
endef

# call BuildPackage - OpenWrt buildroot signature
