#!/bin/sh
[ "$ACTION" = "add" ] && [ "$DEVICENAME" = "br-lan" ] || [ "${DEVICENAME:0:6}" = "qmimux" ] || 
[ "${DEVICENAME:0:4}" = "usb0" ] || exit

exec 512>/var/lock/smp_tune.lock
flock 512 || exit 1

#execute device specific RPS
[ -e "/usr/libexec/platform/packet-steering.sh" ] && {
	/usr/libexec/platform/packet-steering.sh
	exit 0
}

. /lib/functions/smp.sh

default_rps
