include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI Support for DLMS

APP_TLT_NAME:=DLMS Client
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=dlms_client

include ../app.mk

define Package/vuci-app-dlms-ui/description
	DLMS client designed for reading data from COSEM devices and storing read data in local database.
endef

# call BuildPackage - OpenWrt buildroot signature
