include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for NTPD time synchronisation configuration module

APP_TLT_NAME:=NTPD
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=ntpd

include ../app.mk

define Package/vuci-app-ntpd-ui/description
 The ISC ntp suite is a collection of tools used to synchronize the
 system clock with remote NTP time servers and run/monitor local NTP
 servers.
endef

# call BuildPackage - OpenWrt buildroot signature
