#!/bin/sh
# Copyright (C) 2021 Teltonika

LOG_PART="event"

prepare_evtlog() {
	echo "- preparing events-log partition -"

	# prepare jffs2 event-log partition
	local mtd="$(grep -i -m 1 "$LOG_PART" /proc/mtd | cut -c 4- | cut -d ':' -f1)"
	[ -z "$mtd" ] && {
		mkdir -p /overlay/log
		return 0
	}

	# Unlock event-log partition
	mtd unlock "/dev/mtd$mtd"

	# attempt to mount /log
	mount /log && return 0

	echo "- erasing events-log partition -"
	mtd erase "/dev/mtd$mtd"
	mount /log
}

[ "$INITRAMFS" = "1" ] || boot_hook_add preinit_main prepare_evtlog
