include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support Dynamic routes bgp application

APP_DEPENDS:=+SMALL_FLASH:frr8-bgpd +!SMALL_FLASH:frr-bgpd

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
