#!/bin/sh

. /lib/functions.sh

CONF="etherwake"

[ -f "/etc/config/${CONF}" ] || return 0
uci_set "$CONF" "setup" "pathes" "/usr/bin/etherwake /usr/bin/ether-wake /usr/local/usr/bin/etherwake /usr/local/usr/bin/ether-wake"
uci_commit "$CONF"
