#!/bin/sh

. /lib/functions.sh

[ -n "$(uci_get "firewall" "@rule[0]" "priority")" ] && exit 0

priority="1"

add_priority() {
	uci_set "firewall" "$1" "priority" "$priority"
	priority=$((priority + 1))
}

config_load "firewall"
config_foreach add_priority "rule"
uci_commit "firewall"
