#!/bin/sh

. /lib/functions.sh

check_enabled() {
	local section="$1"
	config_get_bool enabled "$section" enabled
	if [ "$enabled" = 1 ]; then 
		uci -q batch <<-EOF
			set network.ipsec_rule='rule'
			set network.ipsec_rule.action_group='lookup'
			set network.ipsec_rule.tos='0'
			set network.ipsec_rule.priority='220'
			set network.ipsec_rule.invert='0'
			set network.ipsec_rule.lookup='220'
		EOF
		uci_commit "network"
		exit 0
	fi
}

config_load "ipsec"
config_foreach check_enabled "remote"

