include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Azure IoT Hub

APP_DEPENDS:=+azure_iothub +vuci-app-data-sender-api-mod-azure

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
