include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for AWS IoT Core
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=aws_iot_core
APP_TLT_NAME:=AWS IoT Core

include ../app.mk

define Package/vuci-app-aws-ui/description
	AWS IoT Core is a utility meant to interact with Amazon Web Services cloud platform. 
	It provides AWS IoT Core Jobs support that lets the device be controlled 
	from AWS IoT Core platform by using device's API.
endef

# call BuildPackage - OpenWrt buildroot signature
