include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Auto Reboot

APP_DEPENDS:=+reboot_utils +reboot_utils-periodic +reboot_utils-ping

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
