include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI UI Support for miniDLNA

APP_TLT_NAME:=DLNA
APP_ROUTER:=$(TLT_PLATFORM_NAME)
APP_APP_NAME:=tlt-minidlna
APP_HW_INFO:=usb/sd_card

include ../app.mk

define Package/vuci-app-minidlna-ui/description
  MiniDLNA is a lightweight DLNA/UPnP media server. It serves
  media files (music, pictures, and video) to clients on a network.
endef

# call BuildPackage - OpenWrt buildroot signature
