include $(TOPDIR)/rules.mk

APP_TITLE:=Spanish Language Support (Español)
LANGUAGE:=es
LANG_LONG_NAME:=spanish
LANGUAGE_STRING:=Español

VERSION:=2023-03-02

include ../lang.mk

# call BuildPackage - OpenWrt buildroot signature
