#
# Copyright (C) 2023 Teltonika
#

include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/download.mk

PKG_NAME:=modem_logger

PKG_SOURCE_VERSION:=7.10

PKG_LICENSE:=Teltonika-closed

include $(INCLUDE_DIR)/package.mk

define Package/$(PKG_NAME)
	SECTION:=utils
	CATEGORY:=Utilities
	TITLE:=Modem logging tool by Teltonika
	DEPENDS:=+libusb-1.0 +libstdcpp +libpthread

	PKG_TLT_NAME:=Modem Logger
	PKG_ROUTER:=$(TLT_PLATFORM_NAME)
	PKG_HIDDEN:=1
endef

define Package/$(PKG_NAME)/description
	Modem firmware logging tool by Teltonika
endef


define Package/$(PKG_NAME)/install
	$(INSTALL_DIR) $(1)/usr/bin

	$(INSTALL_BIN) $(PKG_BUILD_DIR)/qlog $(1)/usr/bin/qlog

	#If not one of the listed PLATFORMS install diag_saver and qc_trace_collector
	$(if $(TLT_PLATFORM_TRB2)$(TLT_PLATFORM_TRB2M)$(TLT_PLATFORM_RUT361)$(TLT_PLATFORM_RUT36X)$(TLT_PLATFORM_TCR1)$(TLT_PLATFORM_OTD140)$(TLT_PLATFORM_RUT9M)$(TLT_PLATFORM_RUT2M)$(TLT_PLATFORM_RUT206),,
		$(INSTALL_BIN) $(PKG_BUILD_DIR)/diag_saver $(1)/usr/bin/diag_saver
		$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/qc_trace_collector/qc-trace-collector/linux/qc_trace_collector $(1)/usr/bin/qc_trace_collector
	)

	$(INSTALL_BIN) $(PKG_BUILD_DIR)/modem_logger.sh $(1)/usr/bin/modem_logger
	$(if $(CONFIG_BASEBAND_SUPPORT), \
		$(INSTALL_DIR) $(1)/etc; \
		$(CP) $(PKG_BUILD_DIR)/src/qlog/conf/default.cfg $(1)/etc/modem_logger_default.cfg)
	if [ $(TLT_PLATFORM_RUTM) ]; then \
		$(INSTALL_DIR) $(1)/etc; \
		$(CP) $(PKG_BUILD_DIR)/src/qlog/conf/unisoc_ps_dsp_important_log.conf $(1)/etc/unisoc_ps_dsp_important_log.conf; \
		$(CP) $(PKG_BUILD_DIR)/src/qc_trace_collector/filter/QXDM_Mask_default_telit.dmc $(1)/etc/QXDM_Mask_default_telit.dmc; \
	fi;
endef

$(eval $(call BuildPackage,$(PKG_NAME)))