#!/bin/sh
. /lib/functions.sh

remove_vpn_type() {
	local section="$1"
	uci_remove "firewall" "$section" "vpn_type"
}

config_load firewall
config_foreach "remove_vpn_type"
uci_commit firewall
exit 0
